name: Origins-Reforged
version: ${version}
main: ru.turbovadim.OriginsReforged
description: Paper plugin inspired by the Origins mod by Apace
api-version: '1.20'
author: cometcake575
depend:
  - EnderaLib
  - packetevents
softdepend:
  - Geyser-Spigot
  - AuthMe
  - PlaceholderAPI
  - ViaVersion
  - WorldEdit
  - WorldGuard

permissions:
  originsreforged.default:
    default: true
    description: Default permissions for Origins-Reborn
  originsreforged.exchange:
    default: op
    description: Use /origin exchange to swap origins with another player
  originsreforged.costbypass:
    default: false
    description: Bypass cost of origin swapping
  originsreforged.admin:
    default: op
    description: Use admin commands for Origins-Reborn
    children:
      - originsreforged.flight
      - originsreforged.exchange
  originsreforged.flight:
    default: op
    description: Use /fly

commands:
  origin:
    permission: originsreforged.default
    description: Modify origins
    usage: /<command>
  fly:
    permission: originsreforged.flight
    description: Toggle flight
    usage: /<command>
